package com.compomics.pride_asa_pipeline.gui.view;

import java.awt.Color;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 *
 * @author Niels Hulstaert
 * @author Harald Barsnes
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.getContentPane().setBackground(new Color(255, 255, 255));
    }

    public JPanel getPrideSelectionParentPanel() {
        return prideSelectionParentPanel;
    }

    public JPanel getFileSelectionParentPanel() {
        return fileSelectionParentPanel;
    }

    public JMenuItem getModificationsMenuItem() {
        return editPtmsMenuItem;
    }
    
    public JMenuItem getPipelineConfigurationMenuItem() {
        return editConfigsMenuItem;
    }

    public JPanel getIdentificationsParentPanel() {
        return identificationsParentPanel;
    }

    public JPanel getSummaryParentPanel() {
        return summaryParentPanel;
    }

    public JPanel getMainPanel() {
        return backgroundPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        experimentSelectionPanel = new javax.swing.JPanel();
        experimentSelectionTabbedPane = new javax.swing.JTabbedPane();
        prideSelectionParentPanel = new javax.swing.JPanel();
        fileSelectionParentPanel = new javax.swing.JPanel();
        pipelineResultsPanel = new javax.swing.JPanel();
        pipelineResultTabbedPane = new javax.swing.JTabbedPane();
        summaryParentPanel = new javax.swing.JPanel();
        identificationsParentPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        editConfigsMenuItem = new javax.swing.JMenuItem();
        editPtmsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        backgroundPanel.setBackground(new java.awt.Color(255, 255, 255));

        experimentSelectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Experiment Selection"));
        experimentSelectionPanel.setOpaque(false);

        experimentSelectionTabbedPane.setMinimumSize(new java.awt.Dimension(20, 20));
        experimentSelectionTabbedPane.setPreferredSize(new java.awt.Dimension(20, 20));

        prideSelectionParentPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        prideSelectionParentPanel.setOpaque(false);
        prideSelectionParentPanel.setPreferredSize(new java.awt.Dimension(20, 20));
        prideSelectionParentPanel.setLayout(new java.awt.GridBagLayout());
        experimentSelectionTabbedPane.addTab("PRIDE", prideSelectionParentPanel);

        fileSelectionParentPanel.setOpaque(false);
        fileSelectionParentPanel.setPreferredSize(new java.awt.Dimension(20, 20));
        fileSelectionParentPanel.setLayout(new java.awt.GridBagLayout());
        experimentSelectionTabbedPane.addTab("Pipeline Result File", fileSelectionParentPanel);

        javax.swing.GroupLayout experimentSelectionPanelLayout = new javax.swing.GroupLayout(experimentSelectionPanel);
        experimentSelectionPanel.setLayout(experimentSelectionPanelLayout);
        experimentSelectionPanelLayout.setHorizontalGroup(
            experimentSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(experimentSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(experimentSelectionPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(experimentSelectionTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        experimentSelectionPanelLayout.setVerticalGroup(
            experimentSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
            .addGroup(experimentSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(experimentSelectionPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(experimentSelectionTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pipelineResultsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pipeline Result"));
        pipelineResultsPanel.setOpaque(false);

        pipelineResultTabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        pipelineResultTabbedPane.setMinimumSize(new java.awt.Dimension(20, 20));
        pipelineResultTabbedPane.setPreferredSize(new java.awt.Dimension(20, 20));

        summaryParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        summaryParentPanel.setOpaque(false);
        summaryParentPanel.setLayout(new java.awt.GridBagLayout());
        pipelineResultTabbedPane.addTab("Summary", summaryParentPanel);

        identificationsParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        identificationsParentPanel.setOpaque(false);
        identificationsParentPanel.setRequestFocusEnabled(false);
        identificationsParentPanel.setLayout(new java.awt.GridBagLayout());
        pipelineResultTabbedPane.addTab("Identifications", identificationsParentPanel);

        javax.swing.GroupLayout pipelineResultsPanelLayout = new javax.swing.GroupLayout(pipelineResultsPanel);
        pipelineResultsPanel.setLayout(pipelineResultsPanelLayout);
        pipelineResultsPanelLayout.setHorizontalGroup(
            pipelineResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pipelineResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pipelineResultTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        pipelineResultsPanelLayout.setVerticalGroup(
            pipelineResultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pipelineResultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pipelineResultTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pipelineResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(experimentSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(experimentSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pipelineResultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        fileMenu.setText("File");

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");

        editConfigsMenuItem.setText("Configuration");
        editMenu.add(editConfigsMenuItem);

        editPtmsMenuItem.setText("Modifications");
        editMenu.add(editPtmsMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Close the tool.
     * 
     * @param evt 
     */
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JMenuItem editConfigsMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem editPtmsMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JPanel experimentSelectionPanel;
    private javax.swing.JTabbedPane experimentSelectionTabbedPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel fileSelectionParentPanel;
    private javax.swing.JPanel identificationsParentPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane pipelineResultTabbedPane;
    private javax.swing.JPanel pipelineResultsPanel;
    private javax.swing.JPanel prideSelectionParentPanel;
    private javax.swing.JPanel summaryParentPanel;
    // End of variables declaration//GEN-END:variables
}
