/* 
 * Copyright 2018 compomics.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.compomics.pride_asa_pipeline.core.gui.view;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JRadioButton;

/**
 *
 * @author Niels Hulstaert
 * @author Harald Barsnes
 */
public class IdentificationsFileSelectionPanel extends javax.swing.JPanel {

    private JFileChooser fileChooser;
    private JFileChooser peakFileChooser;

    /**
     * Creates new form FileSelectionPanel
     */
    public IdentificationsFileSelectionPanel() {
        initComponents();
        fileChooser = new JFileChooser();
        peakFileChooser = new JFileChooser();
        fileTypeButtonGroup.add(mzIDRadioButton);
        fileTypeButtonGroup.add(prideXMLradioButton);
        TogglePeakFileInput(!prideXMLradioButton.isSelected());
    }

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public JFileChooser getPeakFileChooser() {
        return peakFileChooser;
    }

    public JLabel getFileSelectionLabel() {
        return fileSelectionLabel;
    }

    public ButtonGroup getFileTypeButtonGroup() {
        return fileTypeButtonGroup;
    }

    public JRadioButton getMzIDRadioButton() {
        return mzIDRadioButton;
    }

    public JLabel getPeakFileNameLabel() {
        return peakFileNameLabel;
    }

    public JLabel getPeakFileSelectionLabel() {
        return peakFileSelectionLabel;
    }

    public JRadioButton getPrideXMLradioButton() {
        return prideXMLradioButton;
    }

    public JButton getSelectPeakFileButton() {
        return selectPeakFileButton;
    }

    public JLabel getFileNameLabel() {
        return fileNameLabel;
    }

    public JButton getProcessButton() {
        return processButton;
    }

    public JButton getSelectFileButton() {
        return selectFileButton;
    }

    public JCheckBox getIncludeIdentificationsFileModificationsCheckBox() {
        return includeIdentificationsFileModificationsCheckBox;
    }

    public JCheckBox getWriteResultCheckBox() {
        return writeResultCheckBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileTypeButtonGroup = new javax.swing.ButtonGroup();
        fileSelectionLabel = new javax.swing.JLabel();
        processButton = new javax.swing.JButton();
        fileNameLabel = new javax.swing.JLabel();
        selectFileButton = new javax.swing.JButton();
        includeIdentificationsFileModificationsCheckBox = new javax.swing.JCheckBox();
        writeResultCheckBox = new javax.swing.JCheckBox();
        peakFileSelectionLabel = new javax.swing.JLabel();
        peakFileNameLabel = new javax.swing.JLabel();
        selectPeakFileButton = new javax.swing.JButton();
        prideXMLradioButton = new javax.swing.JRadioButton();
        mzIDRadioButton = new javax.swing.JRadioButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(50, 50));

        fileSelectionLabel.setText("Select an identifications File");

        processButton.setText("Process");
        processButton.setMaximumSize(new java.awt.Dimension(80, 25));
        processButton.setMinimumSize(new java.awt.Dimension(80, 25));
        processButton.setPreferredSize(new java.awt.Dimension(80, 25));

        fileNameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        selectFileButton.setText("Browse");
        selectFileButton.setMaximumSize(new java.awt.Dimension(80, 25));
        selectFileButton.setMinimumSize(new java.awt.Dimension(80, 25));
        selectFileButton.setPreferredSize(new java.awt.Dimension(80, 25));

        includeIdentificationsFileModificationsCheckBox.setText("Include identifications file Modifications");
        includeIdentificationsFileModificationsCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        includeIdentificationsFileModificationsCheckBox.setIconTextGap(15);

        writeResultCheckBox.setText("Write Result to File");
        writeResultCheckBox.setToolTipText("The output folder can be set on the \"Pipeline configuration\" panel.");
        writeResultCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        writeResultCheckBox.setIconTextGap(15);

        peakFileSelectionLabel.setText("Select peak File(s)");

        peakFileNameLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        selectPeakFileButton.setText("Browse");
        selectPeakFileButton.setMaximumSize(new java.awt.Dimension(80, 25));
        selectPeakFileButton.setMinimumSize(new java.awt.Dimension(80, 25));
        selectPeakFileButton.setPreferredSize(new java.awt.Dimension(80, 25));

        prideXMLradioButton.setSelected(true);
        prideXMLradioButton.setText("PRIDEXML");
        prideXMLradioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prideXMLradioButtonActionPerformed(evt);
            }
        });

        mzIDRadioButton.setText("MZID");
        mzIDRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mzIDRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(fileNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 646, Short.MAX_VALUE)
                        .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(peakFileNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectPeakFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileSelectionLabel)
                            .addComponent(peakFileSelectionLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(prideXMLradioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(includeIdentificationsFileModificationsCheckBox))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mzIDRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(writeResultCheckBox)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {processButton, selectFileButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileSelectionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(selectPeakFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(peakFileSelectionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(peakFileNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(includeIdentificationsFileModificationsCheckBox)
                    .addComponent(prideXMLradioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(writeResultCheckBox)
                    .addComponent(mzIDRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void prideXMLradioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prideXMLradioButtonActionPerformed
        TogglePeakFileInput(false);
    }//GEN-LAST:event_prideXMLradioButtonActionPerformed

    private void mzIDRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mzIDRadioButtonActionPerformed
        TogglePeakFileInput(true);
    }//GEN-LAST:event_mzIDRadioButtonActionPerformed

    private void TogglePeakFileInput(boolean visible) {
        peakFileNameLabel.setVisible(visible);
        peakFileSelectionLabel.setVisible(visible);
        selectPeakFileButton.setVisible(visible);
        revalidate();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JLabel fileSelectionLabel;
    private javax.swing.ButtonGroup fileTypeButtonGroup;
    private javax.swing.JCheckBox includeIdentificationsFileModificationsCheckBox;
    private javax.swing.JRadioButton mzIDRadioButton;
    private javax.swing.JLabel peakFileNameLabel;
    private javax.swing.JLabel peakFileSelectionLabel;
    private javax.swing.JRadioButton prideXMLradioButton;
    private javax.swing.JButton processButton;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JButton selectPeakFileButton;
    private javax.swing.JCheckBox writeResultCheckBox;
    // End of variables declaration//GEN-END:variables
}
