/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.pride_asa_pipeline.gui.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 */
public class ExperimentProcessPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExperimentProcessPanel
     */
    public ExperimentProcessPanel() {
        initComponents();
    }

    public JComboBox getExperimentSelectionComboBox() {
        return experimentSelectionComboBox;
    }

    public JButton getProcessExperimentButton() {
        return processExperimentButton;
    }

    public JCheckBox getFilterCheckBox() {
        return filterCheckBox;
    }

    public JTextField getTaxonomyTextField() {
        return taxonomyTextField;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        experimentSelectionLabel = new javax.swing.JLabel();
        experimentSelectionComboBox = new javax.swing.JComboBox();
        processExperimentButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(0, 32767));
        filterCheckBox = new javax.swing.JCheckBox();
        taxonomyPanel = new javax.swing.JPanel();
        taxonomyLabel = new javax.swing.JLabel();
        taxonomyTextField = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Experiment selection"));
        setMinimumSize(new java.awt.Dimension(10, 10));
        setPreferredSize(new java.awt.Dimension(300, 100));
        setLayout(new java.awt.GridBagLayout());

        experimentSelectionLabel.setText("Select an experiment");
        experimentSelectionLabel.setMaximumSize(new java.awt.Dimension(135, 30));
        experimentSelectionLabel.setMinimumSize(new java.awt.Dimension(135, 30));
        experimentSelectionLabel.setPreferredSize(new java.awt.Dimension(135, 30));
        experimentSelectionLabel.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(experimentSelectionLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        add(experimentSelectionComboBox, gridBagConstraints);

        processExperimentButton.setText("process");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(processExperimentButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(filler1, gridBagConstraints);

        filterCheckBox.setText("Filter on taxonomy");
        filterCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        filterCheckBox.setMaximumSize(new java.awt.Dimension(135, 30));
        filterCheckBox.setMinimumSize(new java.awt.Dimension(135, 30));
        filterCheckBox.setPreferredSize(new java.awt.Dimension(135, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(filterCheckBox, gridBagConstraints);

        taxonomyPanel.setLayout(new java.awt.GridBagLayout());

        taxonomyLabel.setText("taxonomy ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        taxonomyPanel.add(taxonomyLabel, gridBagConstraints);

        taxonomyTextField.setMinimumSize(new java.awt.Dimension(70, 25));
        taxonomyTextField.setPreferredSize(new java.awt.Dimension(70, 25));
        taxonomyPanel.add(taxonomyTextField, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        add(taxonomyPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox experimentSelectionComboBox;
    private javax.swing.JLabel experimentSelectionLabel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JCheckBox filterCheckBox;
    private javax.swing.JButton processExperimentButton;
    private javax.swing.JLabel taxonomyLabel;
    private javax.swing.JPanel taxonomyPanel;
    private javax.swing.JTextField taxonomyTextField;
    // End of variables declaration//GEN-END:variables
}
