package com.compomics.pride_asa_pipeline.gui.view;

import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Niels Hulstaert
 * @author Harald Barsnes
 */
public class IdentificationsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExperimentDetailPanel
     */
    public IdentificationsPanel() {
        initComponents();
        identificationsTabelScrollPane.getViewport().setOpaque(false);
        identificationsTable.getTableHeader().setReorderingAllowed(false);
        identificationsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    }

    public JTable getIdentificationsTable() {
        return identificationsTable;
    }

    public JPanel getIdentificationDetailPanel() {
        return identificationDetailPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        identificationsTablePanel = new javax.swing.JPanel();
        identificationsTabelScrollPane = new javax.swing.JScrollPane();
        identificationsTable = new javax.swing.JTable();
        identificationDetailPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(520, 520));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(520, 520));

        identificationsTablePanel.setBackground(new java.awt.Color(255, 255, 255));
        identificationsTablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Identifications"));
        identificationsTablePanel.setMinimumSize(new java.awt.Dimension(20, 20));
        identificationsTablePanel.setOpaque(false);
        identificationsTablePanel.setPreferredSize(new java.awt.Dimension(20, 20));

        identificationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        identificationsTabelScrollPane.setViewportView(identificationsTable);

        org.jdesktop.layout.GroupLayout identificationsTablePanelLayout = new org.jdesktop.layout.GroupLayout(identificationsTablePanel);
        identificationsTablePanel.setLayout(identificationsTablePanelLayout);
        identificationsTablePanelLayout.setHorizontalGroup(
            identificationsTablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 0, Short.MAX_VALUE)
            .add(identificationsTablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(identificationsTablePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(identificationsTabelScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        identificationsTablePanelLayout.setVerticalGroup(
            identificationsTablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 174, Short.MAX_VALUE)
            .add(identificationsTablePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(identificationsTablePanelLayout.createSequentialGroup()
                    .add(identificationsTabelScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        identificationDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Identification Details"));
        identificationDetailPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        identificationDetailPanel.setOpaque(false);
        identificationDetailPanel.setPreferredSize(new java.awt.Dimension(20, 20));
        identificationDetailPanel.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(identificationDetailPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .add(identificationsTablePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(identificationsTablePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(identificationDetailPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel identificationDetailPanel;
    private javax.swing.JScrollPane identificationsTabelScrollPane;
    private javax.swing.JTable identificationsTable;
    private javax.swing.JPanel identificationsTablePanel;
    // End of variables declaration//GEN-END:variables
}
