/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.pride_asa_pipeline.gui.view;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Niels Hulstaert
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public JPanel getExperimentSelectionParentPanel() {
        return experimentSelectionParentPanel;
    }

    public JPanel getPipelinePanel() {
        return pipelinePanel;
    }

    public JPanel getModificationsParentPanel() {
        return modificationsParentPanel;
    }

    public JButton getModificationsButton() {
        return modificationsButton;
    }

    public JButton getPipelineButton() {
        return pipelineButton;
    }

    public JButton getPipelineParamsButton() {
        return pipelineParamsButton;
    }

    public JPanel getIdentificationsParentPanel() {
        return identificationsParentPanel;
    }

    public JPanel getSummaryParentPanel() {
        return summaryParentPanel;
    }

    public JPanel getPipelineParamsParentPanel() {
        return pipelineParamsParentPanel;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }       
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toolBar = new javax.swing.JToolBar();
        pipelineButton = new javax.swing.JButton();
        pipelineParamsButton = new javax.swing.JButton();
        modificationsButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        pipelinePanel = new javax.swing.JPanel();
        experimentSelectionParentPanel = new javax.swing.JPanel();
        pipelineResultTabbedPane = new javax.swing.JTabbedPane();
        summaryParentPanel = new javax.swing.JPanel();
        identificationsParentPanel = new javax.swing.JPanel();
        modificationsParentPanel = new javax.swing.JPanel();
        pipelineParamsParentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 900));

        toolBar.setBorder(null);
        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        pipelineButton.setText("Pipeline");
        pipelineButton.setFocusable(false);
        pipelineButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pipelineButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(pipelineButton);

        pipelineParamsButton.setText("Pipeline configuration");
        pipelineParamsButton.setFocusable(false);
        pipelineParamsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pipelineParamsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(pipelineParamsButton);

        modificationsButton.setText("Modifications configuration");
        modificationsButton.setFocusable(false);
        modificationsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modificationsButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(modificationsButton);

        mainPanel.setLayout(new java.awt.CardLayout());

        pipelinePanel.setLayout(new java.awt.GridBagLayout());

        experimentSelectionParentPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        experimentSelectionParentPanel.setPreferredSize(new java.awt.Dimension(20, 20));
        experimentSelectionParentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.25;
        pipelinePanel.add(experimentSelectionParentPanel, gridBagConstraints);

        pipelineResultTabbedPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Pipeline result"));
        pipelineResultTabbedPane.setMinimumSize(new java.awt.Dimension(20, 20));
        pipelineResultTabbedPane.setPreferredSize(new java.awt.Dimension(20, 20));

        summaryParentPanel.setLayout(new java.awt.GridBagLayout());
        pipelineResultTabbedPane.addTab("Summary", summaryParentPanel);

        identificationsParentPanel.setRequestFocusEnabled(false);
        identificationsParentPanel.setLayout(new java.awt.GridBagLayout());
        pipelineResultTabbedPane.addTab("Identifications", identificationsParentPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.75;
        pipelinePanel.add(pipelineResultTabbedPane, gridBagConstraints);

        mainPanel.add(pipelinePanel, "pipelinePanel");

        modificationsParentPanel.setLayout(new java.awt.GridBagLayout());
        mainPanel.add(modificationsParentPanel, "modificationsParentPanel");

        pipelineParamsParentPanel.setLayout(new java.awt.GridBagLayout());
        mainPanel.add(pipelineParamsParentPanel, "pipelineParamsParentPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel experimentSelectionParentPanel;
    private javax.swing.JPanel identificationsParentPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton modificationsButton;
    private javax.swing.JPanel modificationsParentPanel;
    private javax.swing.JButton pipelineButton;
    private javax.swing.JPanel pipelinePanel;
    private javax.swing.JButton pipelineParamsButton;
    private javax.swing.JPanel pipelineParamsParentPanel;
    private javax.swing.JTabbedPane pipelineResultTabbedPane;
    private javax.swing.JPanel summaryParentPanel;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
