package com.compomics.pride_asa_pipeline.gui.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 * @author Harald Barsnes
 */
public class PrideSelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExperimentSelectionPanel
     */
    public PrideSelectionPanel() {
        initComponents();
    }

    public JButton getProcessButton() {
        return experimentProcessButton;
    }

    public JComboBox getExperimentSelectionComboBox() {
        return experimentSelectionComboBox;
    }

    public JCheckBox getTaxonomyFilterCheckBox() {
        return taxonomyFilterCheckBox;
    }

    public JTextField getTaxonomyTextField() {
        return taxonomyTextField;
    }

    public JCheckBox getWriteResultCheckBox() {
        return writeResultCheckBox;
    }

    public JCheckBox getIncludePrideModificationsCheckBox() {
        return includePrideModificationsCheckBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        experimentSelectionLabel = new javax.swing.JLabel();
        experimentSelectionComboBox = new javax.swing.JComboBox();
        taxonomyFilterCheckBox = new javax.swing.JCheckBox();
        taxonomyLabel = new javax.swing.JLabel();
        taxonomyTextField = new javax.swing.JTextField();
        experimentProcessButton = new javax.swing.JButton();
        writeResultCheckBox = new javax.swing.JCheckBox();
        includePrideModificationsCheckBox = new javax.swing.JCheckBox();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(50, 20));

        experimentSelectionLabel.setText("Select a PRIDE Experiment");

        taxonomyFilterCheckBox.setText("Filter on Taxonomy");
        taxonomyFilterCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        taxonomyFilterCheckBox.setIconTextGap(15);

        taxonomyLabel.setText("Taxonomy ID");

        taxonomyTextField.setMinimumSize(new java.awt.Dimension(69, 25));
        taxonomyTextField.setPreferredSize(new java.awt.Dimension(69, 25));

        experimentProcessButton.setText("Process");
        experimentProcessButton.setMaximumSize(new java.awt.Dimension(80, 25));
        experimentProcessButton.setMinimumSize(new java.awt.Dimension(80, 25));
        experimentProcessButton.setPreferredSize(new java.awt.Dimension(80, 25));

        writeResultCheckBox.setText("Write Result to File");
        writeResultCheckBox.setToolTipText("The output folder can be set on the \"Pipeline configuration\" panel.");
        writeResultCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        writeResultCheckBox.setIconTextGap(15);

        includePrideModificationsCheckBox.setText("Incude PRIDE Modifications");
        includePrideModificationsCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        includePrideModificationsCheckBox.setIconTextGap(15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(experimentSelectionComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(experimentSelectionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(taxonomyFilterCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(taxonomyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(taxonomyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(includePrideModificationsCheckBox)
                            .addComponent(experimentProcessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(writeResultCheckBox))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(experimentSelectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(experimentSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(taxonomyFilterCheckBox)
                    .addComponent(taxonomyLabel)
                    .addComponent(taxonomyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(includePrideModificationsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(writeResultCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(experimentProcessButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton experimentProcessButton;
    private javax.swing.JComboBox experimentSelectionComboBox;
    private javax.swing.JLabel experimentSelectionLabel;
    private javax.swing.JCheckBox includePrideModificationsCheckBox;
    private javax.swing.JCheckBox taxonomyFilterCheckBox;
    private javax.swing.JLabel taxonomyLabel;
    private javax.swing.JTextField taxonomyTextField;
    private javax.swing.JCheckBox writeResultCheckBox;
    // End of variables declaration//GEN-END:variables
}
