/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.pride_asa_pipeline.gui.view;

import javax.swing.JPanel;

/**
 *
 * @author niels
 */
public class SummaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form SummaryPanel
     */
    public SummaryPanel() {
        initComponents();
    }

    public JPanel getPieChartParentPanel() {
        return pieChartParentPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieChartParentPanelgg = new javax.swing.JPanel();
        pieChartParentPanel1 = new javax.swing.JPanel();
        pieChartParentPanel2 = new javax.swing.JPanel();
        pieChartParentPanel = new javax.swing.JPanel();

        pieChartParentPanelgg.setBorder(javax.swing.BorderFactory.createTitledBorder("Identifications summary"));
        pieChartParentPanelgg.setLayout(new java.awt.GridBagLayout());

        pieChartParentPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identifications summary"));
        pieChartParentPanel1.setLayout(new java.awt.GridBagLayout());

        pieChartParentPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identifications summary"));
        pieChartParentPanel2.setLayout(new java.awt.GridBagLayout());

        pieChartParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Identifications summary"));
        pieChartParentPanel.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pieChartParentPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pieChartParentPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pieChartParentPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pieChartParentPanelgg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pieChartParentPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pieChartParentPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(pieChartParentPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(pieChartParentPanelgg, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pieChartParentPanel;
    private javax.swing.JPanel pieChartParentPanel1;
    private javax.swing.JPanel pieChartParentPanel2;
    private javax.swing.JPanel pieChartParentPanelgg;
    // End of variables declaration//GEN-END:variables
}
