/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.compomics.pride_asa_pipeline.gui.view;

import javax.swing.JPanel;

/**
 *
 * @author Niels Hulstaert
 */
public class SummaryPanel extends javax.swing.JPanel {

    /**
     * Creates new form SummaryPanel
     */
    public SummaryPanel() {
        initComponents();
    }

    public JPanel getIdentificationsChartParentPanel() {
        return identificationsChartParentPanel;
    }

    public JPanel getModificationsChartParentPanel() {
        return modificationsChartParentPanel;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        identificationsChartParentPanel = new javax.swing.JPanel();
        modificationsChartParentPanel = new javax.swing.JPanel();
        generalSummaryPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(400, 200));
        setLayout(new java.awt.GridBagLayout());

        identificationsChartParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        identificationsChartParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Identifications"));
        identificationsChartParentPanel.setOpaque(false);
        identificationsChartParentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        add(identificationsChartParentPanel, gridBagConstraints);

        modificationsChartParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        modificationsChartParentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Modifications"));
        modificationsChartParentPanel.setOpaque(false);
        modificationsChartParentPanel.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        add(modificationsChartParentPanel, gridBagConstraints);

        generalSummaryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("General"));
        generalSummaryPanel.setOpaque(false);
        generalSummaryPanel.setPreferredSize(new java.awt.Dimension(12, 23));

        org.jdesktop.layout.GroupLayout generalSummaryPanelLayout = new org.jdesktop.layout.GroupLayout(generalSummaryPanel);
        generalSummaryPanel.setLayout(generalSummaryPanelLayout);
        generalSummaryPanelLayout.setHorizontalGroup(
            generalSummaryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 388, Short.MAX_VALUE)
        );
        generalSummaryPanelLayout.setVerticalGroup(
            generalSummaryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 127, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.5;
        add(generalSummaryPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel generalSummaryPanel;
    private javax.swing.JPanel identificationsChartParentPanel;
    private javax.swing.JPanel modificationsChartParentPanel;
    // End of variables declaration//GEN-END:variables
}
