/*
 *

 */
package com.compomics.pride_asa_pipeline.gui.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Niels Hulstaert
 */
public class PrideSelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExperimentSelectionPanel
     */
    public PrideSelectionPanel() {
        initComponents();
    }

    public JButton getProcessButton() {
        return experimentProcessButton;
    }

    public JComboBox getExperimentSelectionComboBox() {
        return experimentSelectionComboBox;
    }

    public JCheckBox getTaxonomyFilterCheckBox() {
        return taxonomyFilterCheckBox;
    }

    public JTextField getTaxonomyTextField() {
        return taxonomyTextField;
    }       

    public JCheckBox getWriteResultCheckBox() {
        return writeResultCheckBox;
    }        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        experimentSelectionLabel = new javax.swing.JLabel();
        experimentSelectionComboBox = new javax.swing.JComboBox();
        taxonomyFilterCheckBox = new javax.swing.JCheckBox();
        taxonomyLabel = new javax.swing.JLabel();
        taxonomyTextField = new javax.swing.JTextField();
        experimentProcessButton = new javax.swing.JButton();
        writeResultCheckBox = new javax.swing.JCheckBox();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(50, 20));

        experimentSelectionLabel.setText("select a pride experiment");

        taxonomyFilterCheckBox.setText("filter on taxonomy");
        taxonomyFilterCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        taxonomyLabel.setText("taxonomy ID");

        taxonomyTextField.setMinimumSize(new java.awt.Dimension(69, 20));
        taxonomyTextField.setPreferredSize(new java.awt.Dimension(69, 20));

        experimentProcessButton.setText("process");
        experimentProcessButton.setMaximumSize(new java.awt.Dimension(80, 25));
        experimentProcessButton.setMinimumSize(new java.awt.Dimension(80, 25));
        experimentProcessButton.setPreferredSize(new java.awt.Dimension(80, 25));

        writeResultCheckBox.setText("write result to file");
        writeResultCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(experimentSelectionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(experimentSelectionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(taxonomyFilterCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(taxonomyLabel))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(writeResultCheckBox)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taxonomyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(experimentProcessButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(experimentSelectionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(experimentSelectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxonomyTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(taxonomyFilterCheckBox)
                        .addComponent(taxonomyLabel)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(experimentProcessButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(writeResultCheckBox)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton experimentProcessButton;
    private javax.swing.JComboBox experimentSelectionComboBox;
    private javax.swing.JLabel experimentSelectionLabel;
    private javax.swing.JCheckBox taxonomyFilterCheckBox;
    private javax.swing.JLabel taxonomyLabel;
    private javax.swing.JTextField taxonomyTextField;
    private javax.swing.JCheckBox writeResultCheckBox;
    // End of variables declaration//GEN-END:variables
}
